# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        stages: [commit]
        entry: rye test
        args: []
        pass_filenames: false
        language: python
default_install_hook_types: [pre-commit, pre-push]
